Make clock rate function
CompEvol/beast2 pull request #953
Opened 2021-03-07 13:04 UTC by Anaphory

Sometimes, it's useful to compute clock rates from other inputs, using eg. the expression calculatiors in BEAST or feast. (In my particular use case, I know the substitution rate 1→0 in an ascertained binary model, so I need to derive it from the inferred frequency of 0s.) There are very few locations in the BEAST code that actually rely on clock rates being parameters, instead of more generic Function objects, so this small patch makes the behaviour more generic, but keeps those things in place by explicit isinstance tests. It should therefore be backwards compatible.

2021-03-08 08:53 UTC, tgvaughan requested changes
Hi @Anaphory, while I agree with the goal, I'd use an intanceof check instead of a try-catch to wrap the RealParameter-specific stuff in initAndValidate.  Any chance you can change that?

2021-03-17 22:06 UTC, Anaphory commented
@tgvaughan like this?

2021-03-18 12:44 UTC, tgvaughan approved these changes

2021-03-18 12:45 UTC, tgvaughan commented
Okay to merge @rbouckaert ?

2021-04-10 08:21 UTC, Anaphory commented
Any other comments on this?

2021-07-07 11:46 UTC, Anaphory commented
@rbouckaert Is there anything about this PR that still needs fixing, or is it just other priorities that prevent it from having been merged?

2021-07-29 20:23 UTC, rbouckaert commented
Sorry for the delay -- I needed to test some BEAUti stuff. Looks all good now.

2021-07-29 20:23 UTC, merged

2021-07-30 01:16 UTC, rbouckaert commented
Hmm, this causes API changes, which should only happen at major revisions. I reverted the merged commits, but will recommit for v2.7.